build:
  cuda_version: "11.8.0"
  system_packages:
    - "libssl-dev"
    - "gcc"
    - "libgl1-mesa-glx"
    - "libglib2.0-0"
    - "curl"
  python_packages:
    - "transformers>=4.34.1"
    - "safetensors>=0.4.0"
    - "opencv-python>=4.8.1.78"
    - "accelerate>=0.24.0"
    - "git+https://github.com/holwech/diffusers.git@visoid"
    - "controlnet-aux>=0.0.7"
    - "compel>=2.0.2"
    - "azure-storage-blob>=12.18.3"
    - "'pydantic>=1.4.0,<2'"
    - "git+https://github.com/holwech/Real-ESRGAN.git"
    - "pyopenssl>=23.3.0"
    - "cryptography>=41.0.5"
    - "'torch>=2.0.0,!=2.0.1,!=2.1.0'"
    - "huggingface-hub"
